version: "3.5"

services:
  db:
    image: postgres:latest
    hostname: db
    container_name: db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: rinha_bank_dev
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1